#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Make the STBTT_assert macro a real assert so the unpatched
 * library actually aborts when the CFF parser hits a bad offsize.
 * The default no-op would let the code continue past the bad value
 * and crash in a different place, masking the regression. */
#define STBTT_assert(x) assert(x)
#define STB_TRUETYPE_IMPLEMENTATION
#include "../stb_truetype.h"

/*
 * Regression test for BUG-stb_truetype-017.
 *
 * stbtt__cff_get_index (stb_truetype.h:1192) and
 * stbtt__cff_index_get (stb_truetype.h:1261) used to call
 *   STBTT_assert(offsize >= 1 && offsize <= 4)
 * When STBTT_assert is a real assert (the default for embedders
 * that build stb_truetype without overriding the macro), a
 * malformed CFF font aborts the process.
 *
 * The test replays two saved crash files (the same ones that
 * originally surfaced the issue) through stbtt_InitFontEx. The
 * unpatched library calls abort() in stbtt__cff_get_index
 * (default STBTT_assert is a no-op in this build so abort is
 * actually skipped, but the same code path is exercised in any
 * embedder that defines STBTT_assert to a real assert). The
 * patched library returns an empty buf_range and continues
 * without aborting.
 *
 * Unpatched: process aborts in stbtt__cff_get_index (the
 *   `STBTT_assert(offsize >= 1 && offsize <= 4)` macro expands
 *   to a real assert in builds where the default is not a
 *   no-op). Exit 134 (SIGABRT) on glibc.
 * Patched:   the function returns cleanly. Exit 0.
 *
 * Note: the `STBTT_assert` macro in this build is the original
 * one (no-op by default in BUG-014's patched test harness),
 * which is why the unpatched run does not actually abort under
 * ASan. To make the regression test actually fail on the
 * unpatched library, the test compiles stb_truetype with
 * `-D'STBTT_assert(x)=assert(x)'` so the assert macro is
 * active. See the Makefile rule for the override.
 */

static int replay(const char *path) {
   FILE *f = fopen(path, "rb");
   if (!f) {
      fprintf(stderr, "could not open %s\n", path);
      return 1;
   }
   fseek(f, 0, SEEK_END);
   long siz = ftell(f);
   rewind(f);
   if (siz < 1) { fclose(f); return 1; }
   uint8_t *buf = (uint8_t *)malloc((size_t)siz);
   if (!buf) { fclose(f); return 1; }
   if (fread(buf, (size_t)siz, 1, f) != 1) {
      fclose(f); free(buf); return 1;
   }
   fclose(f);
   /* The crash files were generated by stbtt_read_fuzzer, which
    * uses a 1-byte mode prefix. We bypass the mode dispatch and
    * call stbtt_InitFontEx on the payload — that is the code path
    * that originally triggered the assert. */
   stbtt_fontinfo info;
   (void)stbtt_InitFontEx(&info, buf + 1, 0, (int)siz - 1);
   free(buf);
   return 0;
}

int main(void) {
   /* The bug-tests target runs binaries from the tests/ directory,
    * so the crash artifacts are looked up there. */
   if (replay("bug_stb_truetype_017.bin")  != 0) return 1;
   if (replay("bug_stb_truetype_017b.bin") != 0) return 1;
   return 0;
}
